# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{arel-sybase-visitor}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mirek Rusin", "Marcello Barnaba"]
  s.date = %q{2011-01-12}
  s.description = %q{Sybase ASE doesn't implement LIMIT and OFFSET. This visitor implements them for usage with arel's .limit() and .offset()}
  s.email = ["mirek@me.com", "vjt@openssl.it"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".autotest",
    "History.txt",
    "MIT-LICENSE.txt",
    "Manifest.txt",
    "README.markdown",
    "Rakefile",
    "arel-sybase-visitor.gemspec",
    "lib/arel/visitors/sybase.rb"
  ]
  s.homepage = %q{http://github.com/ifad/arel-sybase-visitor}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.1}
  s.summary = %q{Sybase ASE visitor for AREL}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

